version: '3'

services:
  midgard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    image: midgard
    ports:
      - 8080:8080
    links:
      - pg
      - thormock
    depends_on:
      - pg
      - thormock
  testcode:
    build:
      context: .
      dockerfile: ./build/test/Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    image: midgard-test
    volumes:
      - .:/var/midgard
    ports:
      - 8080:8080
    links:
      - pg
      - thormock
    depends_on:
      - pg
      - thormock
    command: make install test
    environment:
      - PG_HOST=pg
  pg:
    image: timescale/timescaledb:latest-pg11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    command: postgres -c 'max_connections=250'
  thormock:
    build:
      context: ./tools/mockServer
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
