version: '3'

services:
  midgard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    environment: 
      THORCHAIN_HOST: 18.158.69.134:1317
      THORCHAIN_RPC_HOST: 18.158.69.134:26657
      TIMESCALE_USER_NAME: postgres
    image: midgard
    ports:
      - 8080:8080
    links:
      - pg
      - thormock
    depends_on:
      - pg
      - thormock

  testcode:
    build:
      context: .
      dockerfile: ./build/test/Dockerfile
      args:
        thornode_host: thormock:8081
        pg_host: pg
    image: midgard-test
    environment:
      - PG_HOST=pg
    volumes:
      - .:/var/midgard
    ports:
      - 8080:8080
    links:
      - pg
      - thormock
    depends_on:
      - pg
      - thormock
    command: make test-internal

  pg:
    image: timescale/timescaledb:latest-pg11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    command: postgres -c 'max_connections=250'
    volumes: 
      - timescale_data:/var/lib/postgresql/data

  thormock:
    build:
      context: ./tools/mockServer
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081

volumes: 
  timescale_data:
